[project]
name = "crocology"
version = "0.1.0"
description = "A pure python cryptology library"
readme = "README.md"
license = "MIT"
license-files = [ "LICENSE" ]
authors = [
    { name = "Infinitrix cryptography division", email = "maths.club@iiti.ac.in" }
]
keywords = ["python", "cryptography", "cryptology"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Security :: Cryptography",
]
requires-python = ">=3.10"
dependencies = []

[project.urls]
homepage = "https://github.com/tanpsi/crocology"
documentation = "https://github.com/tanpsi/crocology"
source = "https://github.com/tanpsi/crocology"
issues = "https://github.com/tanpsi/crocology/issues"

[dependency-groups]
dev = [
  "pytest",
  "ruff",
  "mypy",
]

[build-system]
requires = ["uv_build>=0.10.6,<0.11.0"]
build-backend = "uv_build"

[tool.mypy]
show_error_codes = true
check_untyped_defs = true
no_implicit_reexport = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
strict_equality = true
strict_bytes = true

[tool.ruff]
line-length = 88
lint.select = ['E', 'F', 'I', 'N', 'W', 'UP', 'RUF']
